import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/app/layouts/header";
import Footer from "@/app/layouts/footer";
import Sidebar from "@/app/layouts/sidebar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-white text-black ">
          <Header />
          <main className=" mx-auto w-full lg:grid lg:grid-cols-12 " style={{height:'85vh'}}>
            <Sidebar></Sidebar>
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
