import "../../public/globals.css";;
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./layouts/Header";
import Footer from "./layouts/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: React.FCC = ({ children }) => {
  return (
      <html>
          <head>
              <title>attendance with next</title>
          </head>
          <body>
            <Header />
            <div>
              {children}
            </div>
            <Footer />
          </body>
      </html>
  );
};
export default RootLayout;
