import '../public/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from './layouts/Header';
import Footer from './layouts/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <Header />
      <body className="content">{children}</body>
      <Footer />
    </div>
  );
}
