import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from './layouts/header'
import Footer from './layouts/footer'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-white text-black ">
          {/* <Header /> */}
            <main className=" mx-auto "style={{height: '85vh'}}>{children}</main>      
          {/* <Footer /> */}
        </div>
      </body>
    </html>
  )
}
